Repository GetStream/stream-chat-react, pull requests merged in 2020-10, with the labels that each got.

#558 chore: bump dependencies
  package.json
  yarn.lock
Labels: dependencies

#568 bump stream-chat to v2.6.0
  package.json
  yarn.lock
Labels: dependencies

#570 fix #569: add nofollow noreferrer noopener to links markdown
  src/utils.js
Labels: bug

#571 feat: VirtualList support message grouping
  src/components/Message/FixedHeightMessage.js
  src/components/MessageList/VirtualizedMessageList.js
  src/components/MessageList/__tests__/VirtualizedMessageList.test.js
  src/components/MessageList/__tests__/__snapshots__/VirtualizedMessageList.test.js.snap
  src/styles/VirtualMessage.scss
  types/index.d.ts
Labels: enhancement

#579 feat: TypingIndicator renders null if typing_events is disabled
  src/components/TypingIndicator/TypingIndicator.js
  src/components/TypingIndicator/__tests__/TypingIndicator.test.js
  src/mock-builders/generator/channel.js
  src/mock-builders/index.js
Labels: enhancement

#581 feat: disable reactions in Message based on channel config
  src/components/Message/MessageCommerce.js
  src/components/Message/MessageLivestream.js
  src/components/Message/MessageSimple.js
  src/components/Message/MessageTeam.js
  src/components/Message/MessageText.js
  src/components/Message/__tests__/MessageCommerce.test.js
  src/components/Message/__tests__/MessageLivestream.test.js
  src/components/Message/__tests__/MessageSimple.test.js
  src/components/Message/__tests__/MessageTeam.test.js
  src/components/Message/__tests__/MessageText.test.js
  src/components/Message/hooks/__tests__/useReactionHandler.test.js
  src/components/Message/hooks/useReactionHandler.js
Labels: enhancement

#580 feat: Thread renders null if replies is disabled
  src/components/Thread/Thread.js
  src/components/Thread/__tests__/Thread.test.js
Labels: enhancement

#583 fix channellist pagination bug
  src/components/ChannelList/hooks/usePaginatedChannels.js
Labels: bug

#585 feat: Input upload disabled based on channel config
  src/components/MessageInput/EditMessageForm.js
  src/components/MessageInput/MessageInputFlat.js
  src/components/MessageInput/MessageInputLarge.js
  src/components/MessageInput/MessageInputSmall.js
  src/components/MessageInput/__tests__/MessageInput.test.js
  src/components/MessageInput/hooks/messageInput.js
Labels: enhancement

#582 add update param to addMessagesSorted
  package.json
  src/components/Channel/Channel.js
  yarn.lock
Labels: dependencies
